// <auto-generated />
using David_Rosario_P2_Ap1.Api.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace David_Rosario_P2_Ap1.Api.Migrations
{
    [DbContext(typeof(Contexto))]
    [Migration("20240304230439_Inicial")]
    partial class Inicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.2");

            modelBuilder.Entity("Library.Models.Accesorios", b =>
                {
                    b.Property<int>("AccesorioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("AccesorioId");

                    b.ToTable("Accesorios");

                    b.HasData(
                        new
                        {
                            AccesorioId = 1,
                            Descripcion = "Camara Trasera"
                        },
                        new
                        {
                            AccesorioId = 2,
                            Descripcion = "Pantalla Interior"
                        },
                        new
                        {
                            AccesorioId = 3,
                            Descripcion = "Interior en Piel"
                        },
                        new
                        {
                            AccesorioId = 4,
                            Descripcion = "Sun Roof"
                        },
                        new
                        {
                            AccesorioId = 5,
                            Descripcion = "Aros de Lujo"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
